apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: mysql:5.7
          name: db
          env:
            - name: MYSQL_DATABASE
              value: exampledb
            - name: MYSQL_USER
              value: exampleuser
            - name: MYSQL_PASSWORD
              value: examplepass
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "1"