---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: web
  name: web
spec:
  ports:
    - nodePort: 31023
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    run: web
  type: NodePort
