---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: wordpressweb
  name: wordpressweb
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: wordpressweb
  type: ClusterIP
