apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-16T10:25:32Z"
  labels:
    run: wordpressweb
  name: wordpressweb
  namespace: default
  resourceVersion: "23779"
  uid: a95e1089-599c-4f33-93d5-5b387ed21b92
spec:
  clusterIP: 10.99.35.136
  clusterIPs:
  - 10.99.35.136
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31023
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: wordpressweb
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
